### ISSUE TITLE
Potential conflict with numba 1.X

### ISSUE THREAD

**Issue by kgrogan87** [IhmeGroup/StanShock#1]
An issue was found in deployment with the JIT compilation with numba. It is suspected that the code may not be compatible with numba 1.X . Picture of the error shown. 
![AFA01C21CA8F4827B0671FCC958B19F9](https://user-images.githubusercontent.com/14866743/61176454-07f91880-a576-11e9-9e25-9a8ea504a6c7.png)

**Comment by corykinney** [comment]
Fixed by fd24fe6415297ccc67b5bb665cb9e84e87864ff3
